#include<iostream>
using namespace std;
 void a(int &i){
    cout<<i<<" ";
 }
 void b(int &i){
    cout<<i<<" ";
 }
#define PI 3.14;
int score =15; 
int main(){
/* int r=5;
 int  area=3.14*r*r;
cout<<"area is:"<<area;
*/
/*int r=5;
double pi=3.14;
double area=pi*r*r;
*/

/*int r=5;
// double pi=3.14;
double area = PI * r * r;
*/
//GLOBAL VARIABLES 
//using reference  sharing of variables can happened in diffrent function 
/*int i=5;
a(i);
b(i);
*/








return 0;

}
